
name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install litecoin for tests
      run: |
        tarball=litecoin.tar.gz
        wget -O "$tarball" https://download.litecoin.org/litecoin-0.21.2.2/linux/litecoin-0.21.2.2-x86_64-linux-gnu.tar.gz
        tar xvzf "$tarball"
        sudo cp -r litecoin-*/* /usr/local
    - name: Install monero wallet cli for tests
      run: |
        tarball=monero-wallet-cli.tar.gz
        wget -O "$tarball" https://downloads.getmonero.org/cli/monero-linux-x64-v0.18.2.2.tar.bz2
        tar xvaf "$tarball"
        sudo cp -r monero-*/* /usr/local/bin/
    - name: Build contract
      run: make all-via-docker
    - name: Run auth_rust tests
      run: cd tests/auth_rust && bash run.sh
    - name: Install ckb-debugger
      run: cd tests/auth_spawn_rust && make install
    - name: Run auth_spawn_rust tests
      run: cd tests/auth_spawn_rust && make all
    - name: Install cardano tools
      run: cd tests/cardano_lock && make install_cardano_tools
    - name: Run cardano tests
      run: cd tests/cardano_lock && make all
    - name: Run ckb-auth-cli tests
      run: cd tools/ckb-auth-cli && cargo test

